# Generated by Django 5.0.7 on 2024-08-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0007_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Audio',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
    ]
