# Generated by Django 5.0.6 on 2024-07-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0002_rename_contraseña_usuario_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Registro',
        ),
    ]
