# Generated by Django 5.0.6 on 2024-07-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
