# Generated by Django 5.0.6 on 2024-07-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0005_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='confirmPassword',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
