# Generated by Django 5.0.7 on 2024-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0006_registro_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Artista', models.CharField(max_length=200)),
                ('Album', models.CharField(blank=True, max_length=200, null=True)),
                ('Genero', models.CharField(blank=True, max_length=100, null=True)),
                ('Audio', models.FileField(blank=True, null=True, upload_to='music/')),
            ],
        ),
    ]
