# Generated by Django 5.0.7 on 2024-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0008_alter_music_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
